### PR TITLE
Upgrade deps to stay in sync with mapnik-packaging

### PR DESCRIPTION
**Pull request by springmeyer**
@BergWerkGIS - I've updated a bunch of mapnik-packaging/mason unix deps. This tracks those changes.

Next actions:

  - [x] Try building, see what might have broken
  - [ ] Publish new SDK once Mapnik core visual tests are updated - tracking that at https://github.com/mapnik/test-data-visual/pull/37 (won't move on that until its more clear that windows will work with upgrades)

### CODE REVIEW

**Comment by springmeyer** [comment]
The build bot did not seem to work for this commit and I don't have time to check the logs. Hoping @BergWerkGIS can run things locally tomorrow to see what might be broken and hopefully get this working.

**Comment by BergWerkGIS** [comment]
Updated deps built fine, but mapnik fails (/cc @artemp):

```
"c:\mb\windows-builds-64\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj" (ClCompile target) (1) ->
(ClCompile target) -> 

  c:\mb\windows-builds-64\packages\mapnik-master\mapnik-gyp\mapnik-sdk\include\boost/spirit/home/support/attributes.hpp(1036): 
error C2672: 'swap': no matching overloaded function found (compiling source file ..\..\src\image_filter_grammar.cpp) [c:\mb\windows-builds-64\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]

  c:\mb\windows-builds-64\packages\mapnik-master\mapnik-gyp\mapnik-sdk\include\boost/spirit/home/support/attributes.hpp(1036): 
error C2784: 'void boost::spirit::swap(boost::spirit::multi_pass<T,Policies> &,boost::spirit::multi_pass<T,Policies> &)': could not deduce template argument for 'boost::spirit::multi_pass<T,Policies> &' from 'mapnik::color' (compiling source file ..\..\src\image_filter_grammar.cpp) [c:\mb\windows-builds-64\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
```

**Comment by artemp** [comment]
Looks like compilation errors related to boost 1.60 -> 1.61 upgrade. @BergWerkGIS could you point me to the whole trace to see what triggers those errors, pls
/cc @springmeyer

**Comment by BergWerkGIS** [comment]
From my point of view ready to merge and publish new SDKs.
Tested x86 and x64 builds.

Some tests are failing but I suppose that's expected until https://github.com/mapnik/test-data-visual/pull/37 lands.

**Comment by springmeyer** [comment]
Thanks @BergWerkGIS - https://github.com/mapnik/test-data-visual/pull/37 is now landed, so I will push a windows-builds commit to get an SDK built. Thanks!

**Pull request merged**
